config/routes.rb
Rails.application.routes.draw do

  get '/bemvindo' => 'home#index'
  root 'home#index'

  resources :phones
  resources :addresses #only: [:new, show]
  resources :contacts #excepy: [:edit]
  resources :kinds

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :contact
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
  belongs_to :kind, optional: true
  has_one :address, :dependent => :destroy
  has_many :phones, :dependent => :destroy

  accepts_nested_attributes_for :address
  accepts_nested_attributes_for :phones, reject_if: :all_blank, allow_destroy: true

  validates :name, presence: true, length: { minimum: 3 }
  validates :email, presence: true
end

app/models/kind.rb
class Kind < ApplicationRecord

	has_many :contacts

end

app/models/phone.rb
class Phone < ApplicationRecord
  belongs_to :contact
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: [:show, :edit, :update, :destroy]
  before_action :set_options_for_select, only: [:new, :edit, :update, :create]
  http_basic_authenticate_with name: "superjumzao", password: "umdoistres", only: :destroy

  # GET /contacts
  # GET /contacts.json
  def index
    @contacts = Contact.order(:name).page(params[:page]).per(15)

  end

  # GET /contacts/1
  # GET /contacts/1.json
  def show
  end

  # GET /contacts/new
  def new
    @contact = Contact.new
    @contact.build_address
    
  end

  # GET /contacts/1/edit
  def edit
    
  end

  # POST /contacts
  # POST /contacts.json
  def create
    @contact = Contact.new(contact_params)

    respond_to do |format|
      if @contact.save
        format.html { redirect_to contacts_path, notice: I18n.t('messages.created') }
        format.json { render :show, status: :created, location: @contact }
      else
        format.html { render :new }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contacts/1
  # PATCH/PUT /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to contacts_path, notice: I18n.t('messages.updated') }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    @contact.destroy
    respond_to do |format|        
      format.html { redirect_to contacts_path, notice: I18n.t('messages.destroy') }
      format.json { head :no_content }
    end
  end

  private

    def set_options_for_select
      @kind_options_for_select = Kind.all
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def contact_params
      params.require(:contact).permit(:name, :email, :kind_id, :rmk, address_attributes: [:street, :city, :state], phones_attributes: [:id, :phone, :_destroy])
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
  def index
  end

end

app/controllers/kinds_controller.rb
class KindsController < ApplicationController
  before_action :set_kind, only: [:show, :edit, :update, :destroy]

  # GET /kinds
  # GET /kinds.json
  def index
    @kinds = Kind.all
  end

  # GET /kinds/1
  # GET /kinds/1.json
  def show
  end

  # GET /kinds/new
  def new
    @kind = Kind.new
  end

  # GET /kinds/1/edit
  def edit
  end

  # POST /kinds
  # POST /kinds.json
  def create
    @kind = Kind.new(kind_params)

    respond_to do |format|
      if @kind.save
        format.html { redirect_to @kind, notice: 'Kind was successfully created.' }
        format.json { render :show, status: :created, location: @kind }
      else
        format.html { render :new }
        format.json { render json: @kind.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /kinds/1
  # PATCH/PUT /kinds/1.json
  def update
    respond_to do |format|
      if @kind.update(kind_params)
        format.html { redirect_to @kind, notice: 'Kind was successfully updated.' }
        format.json { render :show, status: :ok, location: @kind }
      else
        format.html { render :edit }
        format.json { render json: @kind.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /kinds/1
  # DELETE /kinds/1.json
  def destroy
    @kind.destroy
    respond_to do |format|
      format.html { redirect_to kinds_url, notice: 'Kind was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_kind
      @kind = Kind.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def kind_params
      params.require(:kind).permit(:description)
    end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  
	ESTADOS_BRASILEIROS = [
    ["Acre", "AC"],
    ["Alagoas", "AL"],
    ["Amapá", "AP"],
    ["Amazonas", "AM"],
    ["Bahia", "BA"],
    ["Ceará", "CE"],
    ["Distrito Federal", "DF"],
    ["Espírito Santo", "ES"],
    ["Goiás", "GO"],
    ["Maranhão", "MA"],
    ["Mato Grosso", "MT"],
    ["Mato Grosso do Sul", "MS"],
    ["Minas Gerais", "MG"],
    ["Pará", "PA"],
    ["Paraíba", "PB"],
    ["Paraná", "PR"],
    ["Pernambuco", "PE"],
    ["Piauí", "PI"],
    ["Rio de Janeiro", "RJ"],
    ["Rio Grande do Norte", "RN"],
    ["Rio Grande do Sul", "RS"],
    ["Rondônia", "RO"],
    ["Roraima", "RR"],
    ["Santa Catarina", "SC"],
    ["São Paulo", "SP"],
    ["Sergipe", "SE"],
    ["Tocantins", "TO"]
    ]

    def options_for_states(selected)
        options_for_select(ESTADOS_BRASILEIROS, selected)
    end

    def icon(icon, options = {})
      file = File.read("node_modules/bootstrap-icons/icons/#{icon}.svg")
      doc = Nokogiri::HTML::DocumentFragment.parse file
      svg = doc.at_css 'svg'
      if options[:class].present?
        svg['class'] += " " + options[:class]
      end
        doc.to_html.html_safe
    end

end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/home_helper.rb
module HomeHelper

	def mostrar_meu_nome
		"Gabriel Jum"
	end
	
end

app/helpers/kinds_helper.rb
module KindsHelper
end

app/helpers/phones_helper.rb
module PhonesHelper
end

app/views/contacts/_form.html.erb
<br/>

<%= form_with(model: contact, local: true, html: { class:"basic-grey"}) do |form| %>
  
  <h1> <%= t("contact") %> </h1>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :kind_id %>
    <%= collection_select(:contact, :kind_id, @kind_options_for_select, :id, :description) %>
  </div>

  <%= form.fields_for :address do |address_fields| %>
    <div class="field">
      <%= address_fields.label :street, class: "label-edit" %>
      <%= address_fields.text_field :street %>
    </div>

    <div class="field">
      <%= address_fields.label :city %>
      <%= address_fields.text_field :city %>
    </div>
      
    <div class="field">
      <%= address_fields.label :state %>
      <%= address_fields.select :state, options_for_states(@contact.address.state)%>
    </div>  
  <% end %>

  <div id="phones">
    <%= form.fields_for :phones do |phones_fields| %>
      <%= render partial: "phone_fields", locals: { f: phones_fields } %>
    <% end %>

    <div class="field">

      &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <!-- io_adjust -->

      <%= link_to_add_association(icon('plus-square', class: 'bi bi-edit') + ' [Adicionar Telefone]', form , :phones, class: "txt-decoretion-edit") %>
    </div>
  </div>
  <br>


  <div class="field">
    <%= form.label :rmk %>
    <%= form.text_area :rmk %>
  </div>

  <div class="field">
    <%= form.label " " %>
    <%= form.submit "#{t'buttons.send'}", class: "btn btn-primary"%>
    <%= link_to "#{t'buttons.back'}", contacts_path, class: "btn btn-danger" %>

  </div>

  <% if contact.errors.any? %>
    <div id="error_explanation">
      <h2>
          <%= t'global.forms.messages.errors', count: contact.errors.count%>
      </h2>

      <ul>
        <% contact.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  
<% end %>

app/views/contacts/_phone_fields.html.erb
<div class="nested-fields">
	<div class="field">
		<%= f.label :phone %>
		<%= f.text_field :phone, class: "phone-field" %>
		<%= link_to_remove_association('remover', f)%>
	</div>
</div>

app/views/contacts/edit.html.erb
<%= render 'form', contact: @contact %>

app/views/contacts/index.html.erb
<br/>
<div class="basic-grey">  

  <script>
    $.notify("<%= notice %>","success")
  </script>
  
  <h1><%= "#{t('messages.listing')} #{@contacts.model.model_name.human(count: @contacts.count)}" %></h1>

  
    <div class="container">
      <div class="row">
        <h6 class="col-4"><%= t("name") %></h6>
        <h6 class="col-4" style="text-align: center;"><%= t("kind") %></h6>
        <h6 colspan="2"></h6>
      </div>
    </div>

    <div class="container">
      <% @contacts.each do |contact| %>
        <div class="row" style="background: <%= cycle("white", '#f0f0f5')%>">
          <div class="col-4"><%= contact.name %></div>
          <div class="col-4" style="text-align: center;"><%= contact.kind.description %></div>
          <div class="col-4" style="text-align: center;">
            <%= link_to t('buttons.edit'), edit_contact_path(contact), class: "badge bg-secondary btn-io-edit"%> &nbsp;
            <%= link_to t('buttons.destroy'), contact, method: :delete, data: { confirm: t('messages.confirm') }, class: "badge bg-secondary btn-io-edit" %>
          </div>
        </div>
      <% end %>
    </div>

  <div style= "padding-top: 5px;">
    <%= paginate @contacts, window: 2 %>
  </div>
  <br>

  <%= link_to t('buttons.new'), new_contact_path, class: "btn btn-primary" %>
  <%= link_to t('buttons.back'), root_path, class: "btn btn-danger" %>

</div>

app/views/contacts/new.html.erb
<%= render 'form', contact: @contact %>

app/views/contacts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @contact.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @contact.email %>
</p>

<p>
  <strong>Kind:</strong>
  <%= @contact.kind_id %>
</p>

<p>
  <strong>Rmk:</strong>
  <%= @contact.rmk %>
</p>

<%= link_to 'Edit', edit_contact_path(@contact) %> |
<%= link_to 'Back', contacts_path %>

app/views/home/index.html.erb
<br/>
<div class="basic-grey">	
	<h1>Seja bem-vindo!</h1>

	<ul>
		<li>
			<%= icon("list-ul", class: "bi") + " - " %> <%# método definido em application_helper %>
			<%= link_to "Tipos", kinds_path %>
		</li>
		<li>
			<%= icon("telephone", class: "bi") + " - "  %>
			<%= link_to "Contatos", contacts_path %>
		</li>
		
	</ul>
</div>

app/views/kinds/_form.html.erb
<%= form_with(model: kind, local: true, html: { class:"basic-grey"}) do |form| %>
  <% if kind.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(kind.errors.count, "error") %> prohibited this kind from being saved:</h2>

      <ul>
        <% kind.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <h1>Kind</h1>
  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="field">
    <%= form.label " " %>
    <%= form.submit "Enviar", class: "button" %>
    <%= link_to 'Voltar', kinds_path, class: "button" %>
  </div>
<% end %>

app/views/kinds/edit.html.erb
<%= render 'form', kind: @kind %>

app/views/kinds/index.html.erb
<br/>
<div class="basic-grey"> 

  <script>
    $.notify("<%= notice %>","success")
  </script>

  <h1><%= "#{t('messages.listing')} #{@kinds.model.model_name.human(count: @kinds.count)}" %></h1>

  <table>
    <thead class="container">
      <div class="row">
        <h6 class="col-12"> &nbsp;<%= t("description") %> </h6>
        <h6 colspan="1"></h6>
      </div>
    </thead>

    <tbody class="container">
      <% @kinds.each do |kind| %>
        <div class="row">
          <tr style="background: <%= cycle("white", '#f0f0f5')%>">
            <td class="col"><%= kind.description %></td>
            <td class="col"><%= link_to t('buttons.edit'), edit_kind_path(kind) %></td>
            <td class="col"><%= link_to t('buttons.destroy'), kind, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        </div>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Kind', new_kind_path %>
  <%= link_to t('buttons.back'), root_path %>
</div>

app/views/kinds/new.html.erb
<%= render 'form', kind: @kind %>

app/views/kinds/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @kind.description %>
</p>

<%= link_to 'Edit', edit_kind_path(@kind) %> |
<%= link_to 'Back', kinds_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="pt-BR">
  <head>
    <title>Notebook</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js" type="text/javascript"></script>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag params[:controller] %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <%= javascript_include_tag 'notifyjs/notify' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>